version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: voiceflow
      POSTGRES_USER: voiceflow_user
      POSTGRES_PASSWORD: voiceflow_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8002:8000"
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  postgres_data:
  minio_data:
  chroma_data: